## Gradle Properties
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = true
org.gradle.parallel = true
org.gradle.caching = true

## Environment Properties
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.233
neo_version_range=[21.1.230,)
loader_version_range=[4,)

## Mod Properties
mod_group_id = io.github.nebulamodding.planetsplus
mod_version = 0.0.8

mod_id = planetsplus
mod_name = Planets+
mod_description = \
  Adds more planets, moons, and star systems to explore in Ad Astra!\n\
  Now in mod form :D
mod_license = Modified MIT
mod_icon = pack.png
mod_url = https://github.com/Nebula-Modding/Planets-Plus
mod_issues = https://github.com/Nebula-Modding/Planets-Plus/issues
mod_authors = DeadbushCarrot

## Dependencies
ad_astra_version = 1.16.9